// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDevTrail.Infra.Data;

#nullable disable

namespace ProjetoDevTrail.Infra.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20251130213022_creatingDB")]
    partial class creatingDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoDevTrail.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Account_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Client_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 100000L);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Account_Id");

                    b.HasIndex("Client_Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoDevTrail.Api.Models.Client", b =>
                {
                    b.Property<Guid>("Client_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Client_Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ProjetoDevTrail.Api.Models.Transaction", b =>
                {
                    b.Property<Guid>("Transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Origin_Account_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Target_Account_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Transaction_Id");

                    b.HasIndex("Origin_Account_Id");

                    b.HasIndex("Target_Account_Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("ProjetoDevTrail.Api.Models.CurrentAccount", b =>
                {
                    b.HasBaseType("ProjetoDevTrail.Api.Models.Account");

                    b.Property<decimal>("OverdraftLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Current");
                });

            modelBuilder.Entity("ProjetoDevTrail.Api.Models.SavingsAccount", b =>
                {
                    b.HasBaseType("ProjetoDevTrail.Api.Models.Account");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Savings");
                });

            modelBuilder.Entity("ProjetoDevTrail.Api.Models.Account", b =>
                {
                    b.HasOne("ProjetoDevTrail.Api.Models.Client", null)
                        .WithMany("Accounts")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoDevTrail.Api.Models.Transaction", b =>
                {
                    b.HasOne("ProjetoDevTrail.Api.Models.Account", "OriginAccount")
                        .WithMany()
                        .HasForeignKey("Origin_Account_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoDevTrail.Api.Models.Account", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("Target_Account_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OriginAccount");

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("ProjetoDevTrail.Api.Models.Client", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
